// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthorMicrodata: typeof import('./src/components/AuthorMicrodata.vue')['default']
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BaseLayout: typeof import('./src/layouts/base.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    CopyrightNotice: typeof import('./src/components/CopyrightNotice.vue')['default']
    DeepHeading: typeof import('./src/components/DeepHeading.vue')['default']
    GiscusComments: typeof import('./src/components/GiscusComments.vue')['default']
    GiscusCommentsInner: typeof import('./src/components/GiscusCommentsInner.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.9.5_@babel+parser@7.25.3_@types+node@20.17.7_esbuild@0.24.0_sass@1.81.0_typescript@5.6.3/node_modules/iles/dist/client/app/components/Island.vue')['default']
    MeiliSearch: typeof import('./src/components/MeiliSearch.vue')['default']
    Mermaid: typeof import('./src/components/Mermaid.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarItem: typeof import('./src/components/NavBarItem.vue')['default']
    NotFoundSearch: typeof import('./src/components/NotFoundSearch.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar.vue')['default']
    Picture: typeof import('./node_modules/.pnpm/@islands+images@0.8.2/node_modules/@islands/images/src/Picture.vue')['default']
    PlausibleTrigger: typeof import('./src/components/PlausibleTrigger.vue')['default']
    PostHead: typeof import('./src/components/PostHead.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListNav: typeof import('./src/components/PostListNav.vue')['default']
    PostMicrodata: typeof import('./src/components/PostMicrodata.vue')['default']
    PrevNextPost: typeof import('./src/components/PrevNextPost.vue')['default']
    RenderFeed: typeof import('./node_modules/.pnpm/@islands+feed@0.8.1_iles@0.9.5_@babel+parser@7.25.3_@types+node@20.17.7_esbuild@0.24.0_sass@1_roaauizyxcf6z6no6qcty7yp4u/node_modules/@islands/feed/dist/render-feed')['RenderFeed']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchResultHighlight: typeof import('./src/components/SearchResultHighlight.vue')['default']
    SponsorRequest: typeof import('./src/components/SponsorRequest.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    TableOfContentsButton: typeof import('./src/components/TableOfContentsButton.vue')['default']
    TableOfContentsCommon: typeof import('./src/components/TableOfContentsCommon.vue')['default']
    TableOfContentsDrawer: typeof import('./src/components/TableOfContentsDrawer.vue')['default']
    TableOfContentsNode: typeof import('./src/components/TableOfContentsNode.vue')['default']
    TableOfContentsSidebar: typeof import('./src/components/TableOfContentsSidebar.vue')['default']
    TextJustifyFix: typeof import('./src/components/TextJustifyFix.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    VisitorCount: typeof import('./src/components/VisitorCount.vue')['default']
    VisitorCountRealtime: typeof import('./src/components/VisitorCountRealtime.vue')['default']
  }
}
