// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackToTop: typeof import('./src/components/BackToTop.vue')['default']
    BaseFooter: typeof import('./src/components/BaseFooter.vue')['default']
    BaseLayout: typeof import('./src/layouts/base.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    CodeBlock: typeof import('./src/components/CodeBlock.vue')['default']
    CopyButton: typeof import('./src/components/CopyButton.vue')['default']
    CopyrightNotice: typeof import('./src/components/CopyrightNotice.vue')['default']
    FuseSearch: typeof import('./src/components/FuseSearch.vue')['default']
    GiscusComments: typeof import('./src/components/GiscusComments.vue')['default']
    GiscusCommentsInner: typeof import('./src/components/GiscusCommentsInner.vue')['default']
    Head: typeof import('@vueuse/head')['Head']
    HomePage: typeof import('./src/components/HomePage.vue')['default']
    Island: typeof import('./node_modules/.pnpm/iles@0.8.7_ovmyjmuuyckt3r3gpaexj2onji/node_modules/iles/dist/client/app/components/Island.vue')['default']
    Latin: typeof import('./src/components/Latin.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavBarItem: typeof import('./src/components/NavBarItem.vue')['default']
    PaginationBar: typeof import('./src/components/PaginationBar.vue')['default']
    Picture: typeof import('./node_modules/.pnpm/@islands+images@0.8.1/node_modules/@islands/images/src/Picture.vue')['default']
    PlausibleTrigger: typeof import('./src/components/PlausibleTrigger.vue')['default']
    PostHead: typeof import('./src/components/PostHead.vue')['default']
    PostList: typeof import('./src/components/PostList.vue')['default']
    PostListNav: typeof import('./src/components/PostListNav.vue')['default']
    PostMicrodata: typeof import('./src/components/PostMicrodata.vue')['default']
    PrevNextPost: typeof import('./src/components/PrevNextPost.vue')['default']
    RelativeTime: typeof import('./src/components/RelativeTime.vue')['default']
    RenderFeed: typeof import('./node_modules/.pnpm/@islands+feed@0.8.0_iles@0.8.7+vue@3.2.45/node_modules/@islands/feed/dist/render-feed')['RenderFeed']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SponsorRequest: typeof import('./src/components/SponsorRequest.vue')['default']
    TableOfContents: typeof import('./src/components/TableOfContents.vue')['default']
    TableOfContentsCommon: typeof import('./src/components/TableOfContentsCommon.vue')['default']
    TableOfContentsDrawer: typeof import('./src/components/TableOfContentsDrawer.vue')['default']
    TableOfContentsNode: typeof import('./src/components/TableOfContentsNode.vue')['default']
    TableOfContentsSidebar: typeof import('./src/components/TableOfContentsSidebar.vue')['default']
    TextJustifyFix: typeof import('./src/components/TextJustifyFix.vue')['default']
    ThemeSwitcher: typeof import('./src/components/ThemeSwitcher.vue')['default']
    VisitorCount: typeof import('./src/components/VisitorCount.vue')['default']
  }
}
