export default {
  author: 'ouuan',
  authorLink: 'https://github.com/ouuan',
  firstName: 'Yufan',
  lastName: 'You',
  gender: 'male',
  title: "ouuan's blog",
  description: 'ouuan 的博客。',
  startedAt: new Date('2022-07-20T08:00:00Z'),
  repo: 'ouuan/iles-blog',
  branch: 'master',
  giscusRepoId: 'R_kgDOHrOQ9g',
  giscusCategoryId: 'DIC_kwDOHrOQ9s4CQSIu',
  mastodonAccount: 'ouuan',
  mastodonDomain: 'mastodon.online',
} as const;
