name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: # https://stackoverflow.com/a/74341376
      image: node:lts
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fix file ownerships
        run: chown -R "$(whoami):$(whoami)" .
      - run: npx pnpm i
      - run: npx pnpm build
      - name: Check links
        shell: bash
        run: |
          set -xeuo pipefail
          npm exec iles preview &
          sleep 5
          wget -c "$(curl -L https://api.github.com/repos/raviqqe/muffet/releases/latest | jq -r '.assets[] | select(.name | test("Linux_x86_64")) | .browser_download_url')"
          mkdir -p muffet
          tar xf muffet_*_Linux_x86_64.tar.gz -C muffet
          muffet/muffet http://localhost:4173 -i 'http://localhost'
