name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: # https://stackoverflow.com/a/74341376
      image: raviqqe/muffet
    steps:
      - name: Install dependencies
        run: apk add bash git npm
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive
      - name: Fix file ownerships
        run: chown -R "$(whoami):$(whoami)" .
      - run: npx pnpm i
      - run: npx pnpm build
      - name: Check links
        shell: bash
        run: |
          set -xeuo pipefail
          "$(npx pnpm bin)"/iles preview &
          sleep 10
          /muffet http://localhost:4173 -i 'http://localhost'
