name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive
      - uses: pnpm/action-setup@v3
        with:
          version: latest
      - uses: actions/setup-node@v6
        with:
          node-version: 22.21.0
          cache: pnpm
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm typecheck
